// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quaestura.Database;

#nullable disable

namespace Quaestura.Database.Migrations
{
    [DbContext(typeof(QuaesturaDbContext))]
    partial class QuaesturaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quaestura.Database.Entity.Knowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<bool>("IsReferenced")
                        .HasColumnType("boolean")
                        .HasColumnName("is_referenced");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int?>("Subject")
                        .HasColumnType("integer")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Subject", "Grade");

                    b.HasIndex("Subject", "Grade", "Name")
                        .IsUnique();

                    b.ToTable("knowledge");
                });

            modelBuilder.Entity("Quaestura.Database.Entity.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("MistakeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("mistake_id");

                    b.Property<string>("PicturePaths")
                        .HasColumnType("text")
                        .HasColumnName("picture_paths");

                    b.Property<string>("StudentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("student_id");

                    b.Property<int>("Subject")
                        .HasColumnType("integer")
                        .HasColumnName("subject");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("Subject", "Grade");

                    b.HasIndex("Subject", "Grade", "Level");

                    b.HasIndex("Subject", "Grade", "Type");

                    b.ToTable("question");
                });

            modelBuilder.Entity("Quaestura.Database.Entity.QuestionContent", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Analysis")
                        .HasColumnType("text")
                        .HasColumnName("analysis");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("question_content");
                });

            modelBuilder.Entity("Quaestura.Database.Entity.QuestionKnowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeId");

                    b.HasIndex("QuestionId", "KnowledgeId")
                        .IsUnique();

                    b.ToTable("question_knowledge");
                });

            modelBuilder.Entity("Quaestura.Database.Entity.Knowledge", b =>
                {
                    b.HasOne("Quaestura.Database.Entity.Knowledge", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Quaestura.Database.Entity.QuestionContent", b =>
                {
                    b.HasOne("Quaestura.Database.Entity.Question", "Question")
                        .WithOne()
                        .HasForeignKey("Quaestura.Database.Entity.QuestionContent", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quaestura.Database.Entity.QuestionKnowledge", b =>
                {
                    b.HasOne("Quaestura.Database.Entity.Knowledge", "Knowledge")
                        .WithMany("QuestionKnowledges")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quaestura.Database.Entity.Question", "Question")
                        .WithMany("QuestionKnowledges")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledge");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Quaestura.Database.Entity.Knowledge", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("QuestionKnowledges");
                });

            modelBuilder.Entity("Quaestura.Database.Entity.Question", b =>
                {
                    b.Navigation("QuestionKnowledges");
                });
#pragma warning restore 612, 618
        }
    }
}
